project:
  name: "MPESA Fraud Detection"
  version: 1.0

data:
  raw: "./data/mpesa_transactions.csv"

target:
  - isFraud

features:
  - transaction_type
  - amount
  - oldbalanceOrg
  - newbalanceOrig

split:
  test_size: 0.2
  shuffle: shuffle
  random_state: 42
  class_weight: "balanced"

model:
  type: "random_forest"
  parameters:
    n_estimators: 300
    random_state: 42

output:
  "model_dir": "./models/model.pk1"
  "evaluation_report": "./reports/evaluation_report.md"
